TKR-1512 ⚫ [AUTOPTIN] Webhook Magento V1
Send4BR/notification-order-magentov1 pull request #1
Opened 2021-06-08 18:27 UTC by tiagobrunoBFR

### Problema 

O JE precisa receber a informação de pedidos de todas as plataformas, mesmo daquelas que não usem o nosso widget, para viabilizar a implementação do tratamento de todos os e-commerces com o TKR-1007 [AUTOPTIN] Multicanal ativo, BUT a MagentoV1 não possui webhook que nos envie os pedidos criados lá. 

### Solução
Desenvolver uma solução de webhook para a MagentoV1 que possamos utilizar para atender no JE os e-commerces que usam essa plataforma

2021-06-09 12:35 UTC, AndreFilippe requested changes

2021-06-09 12:35 UTC, AndreFilippe commented on code/Aftersale/NotificationOrder/Model/OrderObserver.php
> +require __DIR__ . "/../Services/WebhookServer.php";
vc não conseguiu fazer o autoload das class?

2021-06-09 12:35 UTC, AndreFilippe commented on code/Aftersale/NotificationOrder/Model/OrderObserver.php
> +class Aftersale_NotificationOrder_Model_OrderObserver
Esse nome de class esta fora do padrão
AftersaleNotificationOrderModelOrderObserver

2021-06-09 12:35 UTC, AndreFilippe commented on code/Aftersale/NotificationOrder/Services/OrderNotification.php
> +require __DIR__ . "/SendEmail.php";
vc não conseguiu fazer o autoload das class?

2021-06-09 12:35 UTC, AndreFilippe commented on code/Aftersale/NotificationOrder/Services/OrderNotification.php
> +    public function __construct($webhookServer)
Adicionar a tipagem do parametro

2021-06-09 12:35 UTC, AndreFilippe commented on code/Aftersale/NotificationOrder/Services/OrderNotification.php
> +    public function send($data)
troca o nome da variavel `$data` para algum mais auto-explicativo

2021-06-09 12:35 UTC, AndreFilippe commented on code/Aftersale/NotificationOrder/Services/SendEmail.php
> +    public function __construct($message)
passar a tipagem do paramentro

2021-06-09 12:35 UTC, AndreFilippe commented on code/Aftersale/NotificationOrder/Helper/Data.php
> +class Aftersale_NotificationOrder_Helper_Data extends Mage_Core_Helper_Abstract
Nome da class fora do padrão

2021-06-09 12:37 UTC, tiagobrunoBFR commented on code/Aftersale/NotificationOrder/Model/OrderObserver.php
> +require __DIR__ . "/../Services/WebhookServer.php";
Não, o composer uso somente para os testes, partir do pressuposto dos clientes não usarem o composer e não depender dele para instalar o modulo;

2021-06-09 12:39 UTC, tiagobrunoBFR commented on code/Aftersale/NotificationOrder/Helper/Data.php
> +class Aftersale_NotificationOrder_Helper_Data extends Mage_Core_Helper_Abstract
esse é o padrão de nome de classe da magento

2021-06-24 02:21 UTC, tiagobrunoBFR commented on code/Aftersale/NotificationOrder/Services/OrderNotification.php
> +    public function __construct($webhookServer)
A tipagem de parâmetros só reconhecida na versão 7.4 do php, nesse projeto temos que levar em consideração clientes que utilizam o php legado, na versão 5
https://www.php.net/manual/pt_BR/language.types.declarations.php

2021-06-24 02:21 UTC, tiagobrunoBFR commented on code/Aftersale/NotificationOrder/Services/SendEmail.php
> +    public function __construct($message)
A tipagem de parâmetros só reconhecida na versão 7.4 do php, nesse projeto temos que levar em consideração clientes que utilizam o php legado, na versão 5
https://www.php.net/manual/pt_BR/language.types.declarations.php

2021-06-24 02:27 UTC, tiagobrunoBFR commented on code/Aftersale/NotificationOrder/Services/OrderNotification.php
> +    public function __construct($webhookServer)
Injeção de Dependência não é compatível com versões antigas do php

2021-06-24 12:28 UTC, AndreFilippe approved these changes

2021-06-24 13:42 UTC, luanbrandao requested changes
não tem que adicionar os workflows para rodar os testes no github actions ???

2021-06-24 13:52 UTC, tiagobrunoBFR commented
Vou falar com o @luizhenmariano para me ajudar no github actions

2021-06-24 16:04 UTC, luanbrandao approved these changes

2021-06-24 16:08 UTC, merged